// <auto-generated />
namespace Sampe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sampe2306201818021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sampe2306201818021));
        
        string IMigrationMetadata.Id
        {
            get { return "201806232152226_sampe2306201818021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
