// <auto-generated />
namespace Sampe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sampe220620181410 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sampe220620181410));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221711438_Sampe220620181410"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
