// <auto-generated />
namespace Sampe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sampe2206201814101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sampe2206201814101));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221726149_Sampe2206201814101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
